/** SE CREA LA BASE DE DATOS**/
CREATE DATABASE Semana8_Adriana
GO

/** SE SELECCIONA LA BASE DE DATOS CREADA**/
USE Semana8_Adriana
GO

/** INSTRUCCION QUE PERMITE CREAR LOS DIAGRAMAS**/
Alter authorization on database::Semana8_Adriana to sa 

/*Establece el formato de la fecha en dia/mes/año, 
cualquiera de las dos*/
SET DATEFORMAT dmy  --comentsrio en la linea 
SET LANGUAGE spanish

/*Instruccion que indica que la proxima consulta 
se ejecutará hasta que termine de ejecutarse la sentencia anterior*/
GO 


--Creando tabla cliente
CREATE TABLE CLIENTE(
ID INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NULL,
DIRECCION VARCHAR(250) NULL,
NUM_TELEFONO VARCHAR(9) NULL,
CONSTRAINT [PK_CLIENTE] PRIMARY KEY(ID ASC)
)
GO
--CREANDO LA TABLA CUENTA, QUE CONTIENE LA LLAVE FORANEA
CREATE TABLE CUENTA(
NUM_CUENTA INT NOT NULL,
FEC_APERTURA datetime NOT NULL,
SALDO NUMERIC (10,2) NOT NULL,
ID_CLIENTE INT NOT NULL,
CONSTRAINT PK_CUENTA PRIMARY KEY (NUM_CUENTA ASC),
CONSTRAINT FK_CLIENTE_CUENTA FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID)
)
GO

/*USO COMANDO ALTER*/
-- ALTER TA BLE CLIENTE DROP COLUMN TELEFONO
-- ALTER TABLE CLIENTE ADD TELEFONO VARCHAR(9)

-- INSERTAR CLIENTES

INSERT INTO CLIENTE(ID, NOMBRE, DIRECCION,NUM_TELEFONO)
					VALUES (1, 'JOSE PEREZ', 'HEREDIA', '8564-8951')
INSERT INTO CLIENTE(ID, DIRECCION, NOMBRE, NUM_TELEFONO)
					VALUES (2, 'ALAJUELA', 'ANA CASTRO', '7839-7289')
GO
-- INSERTAR CUENTAS
INSERT INTO CUENTA(NUM_CUENTA, FEC_APERTURA, SALDO,ID_CLIENTE)
					VALUES (12, '26/10/2022', 5000,1)
INSERT INTO CUENTA(NUM_CUENTA, FEC_APERTURA, SALDO,ID_CLIENTE)
					VALUES (13, '26/10/2023', 50000,1)
GO
/* CONSULTAR LOS CLIENTES Y LAS CUEENTAS EXISTENTES*/

SELECT ID, NOMBRE, DIRECCION, NUM_TELEFONO
FROM CLIENTE
SELECT NUM_CUENTA, FEC_APERTURA,SALDO, ID_CLIENTE
FROM CUENTA

GO

/*COMANDO PARA BORRAR LA TABLA*/
DROP TABLE  CLIENTE -- DA ERROR, XQ LA TABLA TIENE PPRESTADO SU LLAVE
-- DEBIDO A QUE EXISTEN CUENTAS QUE YA EXISTE UN NUMERO DE CLIENTE
GO


-- BORRAR

DELETE FROM CLIENTE
WHERE ID=1  --ERROR , EL CLIENTE 1 TIENE DEPENDENCIAS

DELETE FROM CLIENTE
WHERE ID=2 -- NO HAY DEPENDENCIAS

-- MODIFICAR
UPDATE CLIENTE
SET NOMBRE= 'JOSE PEREZ' , DIRECCION= 'ALAJUELA'
WHERE ID=1
/*NO EJECUTAR , SOLO PARA CULTURA GENERAL*/


-- BORRAR LA TABLA CUENTA 
DROP TABLE CUENTA 
GO

-- BORRAR LA TABLA CLIENTE
DROP TABLE CLIENTE
GO

-- BORRAR LA BASE DE DATOS
ALTER DATABASE SEMANA8_Adriana
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
USE MASTER
DROP DATABASE Semana8_Adriana
GO
